---
title: "Travaux exploratoires avec des données satellites : Bilan des résultats obtenus"
subtitle: |
  **[Raya Berova (DMRG), Gaëtan Carrère (SES - DR971), Thomas Faria (SSP Lab), Clément Guillo (SES - DR971), Tom Seimandi (SSP Lab)]{.orange}**
date: "05/28/2024"
date-format: "D MMMM YYYY"
slide-number: true
# uncomment for French presentations:
lang: fr-FR
# for blind readers:
slide-tone: false
chalkboard: # press the B key to toggle chalkboard
  theme: whiteboard
# uncomment to use the multiplex mode:
# multiplex: true
format:
  onyxia-revealjs:
    output-file: index.html
controls: true
css: ../custom.css
ascii: true
---


# Plan de la présentation

1️⃣ Introduction

2️⃣ Méthodologie

3️⃣ Les données 

4️⃣ Résultats obtenus

5️⃣ Structure du projet

6️⃣ Discussion


# 1️⃣ Introduction

{{< include sections/1-introduction.qmd >}}

# Plan de la présentation

1️⃣ Introduction

2️⃣ Méthodologie

3️⃣ Les données 

4️⃣ Résultats obtenus

5️⃣ Structure du projet

6️⃣ Discussion

# 2️⃣ Méthodologie

{{< include sections/3-methodo.qmd >}}

# Plan de la présentation

1️⃣ Introduction

2️⃣ Méthodologie

3️⃣ Les données 

4️⃣ Résultats obtenus

5️⃣ Structure du projet

6️⃣ Discussion

# 3️⃣ Les données 

{{< include sections/2-data.qmd >}}

# Plan de la présentation

1️⃣ Introduction

2️⃣ Méthodologie

3️⃣ Les données 

4️⃣ Résultats obtenus

5️⃣ Structure du projet

6️⃣ Discussion

# 4️⃣ Résultats obtenus

{{< include sections/4-results.qmd >}}

# Plan de la présentation

1️⃣ Introduction

2️⃣ Méthodologie

3️⃣ Les données 

4️⃣ Résultats obtenus

5️⃣ Structure du projet

6️⃣ Discussion

# 5️⃣ Structure du projet

{{< include sections/5-tools.qmd >}}

# Plan de la présentation

1️⃣ Introduction

2️⃣ Méthodologie

3️⃣ Les données 

4️⃣ Résultats obtenus

5️⃣ Structure du projet

6️⃣ Discussion

# 6️⃣ Discussion

{{< include sections/6-discussion.qmd >}}

