---
title: "Usage de l'imagerie Satellitaire et des algorithmes de Deep Learning au service du Recensement de la population dans les DOM"
author:
    - name: Raya Berova
      email: raya.berova@insee.fr
      affiliations: 
          - id: Insee
            name: Insee
            department: DMRG
            city: Montrouge
            postal-code: 92541
    - name: Gaëtan Carrere
      email: gaetan.carrere@insee.fr
      affiliations: 
          - id: Insee
            name: Insee
            department: Dirag
            city: Pointe à Pitre
            postal-code: 971
    - name: Thomas Faria
      email: thomas.faria@insee.fr
      affiliations:
          - id: Insee
            name: Insee
            department: SSP Lab
            city: Montrouge
            postal-code: 92541
    - name: Clément Guillo
      email: clement.guillo@insee.fr
      affiliations: 
          - id: Insee
            name: Insee
            department: Dirag
            city: Pointe à Pitre
            postal-code: 971
    - name: Tom Seimandi
      email: tom.seimandi@insee.fr
      affiliations: 
          - id: Insee
            name: Insee
            department: SSP Lab
            city: Montrouge
            postal-code: 92541
date: last-modified
lang: fr-FR

abstract: |
  La crédibilité des chiffres produits par l'Insee est souvent remise en cause dans les départements d'Outre-Mer. Les chiffres produits par le recensement de la population sont notamment fortement critiqués en Guyane et à Mayotte par les élus locaux ce qui incite l'Insee à travailler sur des sources de données innovantes pour soutenir le discours porté par sa production statistique.
  
  L'utilisation de l'imagerie satellitaire permet d'une part de compléter les estimations produites par l'Insee, en alignant l'évolution du bâti observée sur les images aux évolutions des estimations de population produites par le recensement de la population et d'autre part de soutenir l'opération de repérage des logements sur le terrain en anticipant en amont *via* les images les zones où les mouvements de création ou de destruction sont les plus conséquents.

  Des algorithmes de *deep learning* entraînés sur ces images parviennent à détecter automatiquement les contours du bâti dans les DOM de manière très précise. L'algorithme présentant les meilleures performances a été enveloppé dans une application web à destination des agents en bureau, leur permettant de prendre des décisions à partir des zones exhibées par l'algorithme et des images satellites brutes.

  La chaîne de traitement dans son ensemble allant de la récupération des images jusqu'à l'application web d'aide à la décision, en passant par l'entraînement des algorithmes de *deep learning*, requiert une pluralité de compétences et une forte technicité pour pouvoir être maintenue.


format:
  typst:
    toc: true
    section-numbering: 1.1.a
    columns: 1
    keep-typ: true
    bibliography: biblio.bib
    bibliographystyle: apa
---

{{< pagebreak >}}

# Introduction {.unnumbered}

En Guyane et à Mayotte, les chiffres du recensement de la population sont souvent remis en question par les élus et la population. La confirmation des évolutions observées par l'Insee par des sources externes est donc cruciale. Ce papier vise à présenter les travaux réalisés à l'Insee au sein du projet *"données satellites"* et à expliciter l'apport potentiel des données d'observation du sol. Le projet consiste en l'utilisation d'images satellites pour reconnaître, grâce à de l'intelligence artificielle, la position des logements, ceci afin de diriger plus finement les moyens humains déployés pour l'enquête cartographique et soutenir les estimations produites par l'opération de recensement de la population officielle de l'Insee.

L'équipe projet est constitué d'un agent basé à la Direction Inter-régionale Antilles-Guyane et de trois agents basés au Département de la Méthodologie à la Direction Générale. Ces travaux ont été initiés il y a près d'un an. Les avancées présentées dans ce qui suit sont issues de périodes de travail réalisées de manière saccadée par les membres de l'équipe qui ne peuvent y accorder qu'une partie limitée de leur temps de travail. Deux excellents stages ont été réalisés à l'été 2023, l'un à la Direction Inter-régionale Antilles Guyane, traitant de la détection de logement à partir d'images satellites de très haute résolution [@berova2023](https://minio.lab.sspcloud.fr/cguillo/rapport_stage/Rapport_de_stage_3A-2.pdf), l'autre au Département de la Méthodologie, s'appuyant sur des images de haute résolution [@nabec2023](https://minio.lab.sspcloud.fr/cguillo/rapport_stage/Rapport_de_stage_2023-3.pdf). Durant l'été 2022, un stage a été réalisé sur le sujet plus général de la couverture du sol [@chabennet2021](https://minio.lab.sspcloud.fr/cguillo/rapport_stage/rapport_stage_quentin_dmrg-1.pdf) et a permis une première prise en main du vaste ensemble d'outils mobilisés dans ces travaux.

Ce projet mobilise des compétences variées et sa complexité demande une formation générale sur des sujets différents : manipulation d'images satellites, compréhension de la structure d'une image d'un point de vue informatique, maîtrise des outils de *deep learning* et des méthodes d'entraînement d'algorithmes, documentation à propos de l'avancée de la recherche en intelligence artificielle, compétences de traitement et de mise à disposition des résultats *via* une application... Nous tenterons donc d'aborder et de détailler tous les aspects de ce chantier. Dans un premier temps, nous allons rappeler le contexte de la mise en place de ce groupe de travail autour des données satellites, en dessinant précisément les besoins auxquels il aspire à répondre. Nous nous pencherons dans un second temps sur les données disponibles, les images satellites et leur traitement en amont de toute analyse. Nous rappellerons ensuite le principe des algorithmes de segmentation en *deep learning*, en justifiant d'une part en quoi ils sont pertinents dans le cadre de la détection du bâti, d'autre part en présentant la manière dont nous les avons appliqués à ce problème et à ces données. Cela nous permettra ensuite de détailler l'entraînement des algorithmes et de présenter les prédictions obtenues. Ces prédictions n'étant pas immédiatement exploitables, nous présenterons les traitements effectués *a posteriori* permettant de les rendre utilisables. Ce papier présentera enfin les pistes d'amélioration et de poursuite du projet, ainsi que les perspectives d'utilisation futures. 


{{< include sections/1-introduction.qmd >}}

{{< pagebreak >}}

# Préparation des données 

{{< include sections/2-preparation_donnees.qmd >}}

{{< pagebreak >}}

# Entraînement des algorithmes

{{< include sections/3-algorithme.qmd >}}

{{< pagebreak >}}

# Analyse et mise en forme des sorties

{{< include sections/4-resultats.qmd >}}

{{< pagebreak >}}

# Pistes et évolutions

{{< include sections/5-pistes-evolutions_discussion.qmd >}}
